"""MSCI India August 2026 review — estimated post-review weights and passive
flows, sourced from the user-provided workbook
(MSCI_India_August_2026_Estimated_Weights_and_Flows.xlsx, sheet "166 Stocks - Model").
"""

import re

MSCI_FLOWS = [
    {'stock': 'ETERNAL LIMITED', 'ow': 0.49, 'nw': 1.572, 'chg': 1.082, 'usd': 674.0, 'inr': 6443.4, 'dir': 'BUY', 'conf': 'Reported Nuvama estimate', 'status': 'Post-review constituent'},
    {'stock': 'Laurus Labs', 'ow': 0.0, 'nw': 0.971, 'chg': 0.971, 'usd': 598.0, 'inr': 5716.9, 'dir': 'BUY', 'conf': 'Reported Nuvama estimate', 'status': 'Post-review constituent'},
    {'stock': 'Lenskart Solutions', 'ow': 0.0, 'nw': 0.572, 'chg': 0.572, 'usd': 352.0, 'inr': 3365.1, 'dir': 'BUY', 'conf': 'Reported Nuvama estimate', 'status': 'Post-review constituent'},
    {'stock': 'Adani Energy Solutions', 'ow': 0.0, 'nw': 0.503, 'chg': 0.503, 'usd': 310.0, 'inr': 2963.6, 'dir': 'BUY', 'conf': 'Reported Nuvama estimate', 'status': 'Post-review constituent'},
    {'stock': 'Billionbrains Garage Ventures (Groww)', 'ow': 0.0, 'nw': 0.416, 'chg': 0.416, 'usd': 256.0, 'inr': 2447.4, 'dir': 'BUY', 'conf': 'Reported Nuvama estimate', 'status': 'Post-review constituent'},
    {'stock': 'Adani Enterprises Ltd.', 'ow': 0.42, 'nw': 0.737, 'chg': 0.317, 'usd': 202.0, 'inr': 1931.1, 'dir': 'BUY', 'conf': 'Reported Nuvama estimate', 'status': 'Post-review constituent'},
    {'stock': 'Adani Port and Special Economic Zone Ltd.', 'ow': 0.72, 'nw': 0.827, 'chg': 0.107, 'usd': 77.0, 'inr': 736.1, 'dir': 'BUY', 'conf': 'Reported Nuvama estimate', 'status': 'Post-review constituent'},
    {'stock': 'HDFC Bank Ltd.', 'ow': 6.99, 'nw': 6.818, 'chg': -0.172, 'usd': 4.98, 'inr': 47.6, 'dir': 'BUY', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'ICICI Bank Ltd.', 'ow': 5.6, 'nw': 5.462, 'chg': -0.138, 'usd': 3.99, 'inr': 38.2, 'dir': 'BUY', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'Bharti Airtel Ltd', 'ow': 3.9, 'nw': 3.804, 'chg': -0.096, 'usd': 2.78, 'inr': 26.6, 'dir': 'BUY', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'Axis Bank Ltd.', 'ow': 2.38, 'nw': 2.322, 'chg': -0.058, 'usd': 1.7, 'inr': 16.2, 'dir': 'BUY', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'Infosys Ltd.', 'ow': 2.34, 'nw': 2.283, 'chg': -0.057, 'usd': 1.67, 'inr': 15.9, 'dir': 'BUY', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'Larsen And Toubro Ltd.', 'ow': 2.15, 'nw': 2.097, 'chg': -0.053, 'usd': 1.53, 'inr': 14.7, 'dir': 'BUY', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'Mahindra & Mahindra Ltd.', 'ow': 2.05, 'nw': 2.0, 'chg': -0.05, 'usd': 1.46, 'inr': 14.0, 'dir': 'BUY', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'BAJAJ FINANCE LTD.', 'ow': 1.92, 'nw': 1.873, 'chg': -0.047, 'usd': 1.37, 'inr': 13.1, 'dir': 'BUY', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'KOTAK MAHINDRA BANK LTD.', 'ow': 1.65, 'nw': 1.609, 'chg': -0.041, 'usd': 1.18, 'inr': 11.2, 'dir': 'BUY', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'STATE BANK OF INDIA', 'ow': 1.46, 'nw': 1.424, 'chg': -0.036, 'usd': 1.04, 'inr': 10.0, 'dir': 'BUY', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'Sun Pharmaceuticals Industries Ltd.', 'ow': 1.29, 'nw': 1.258, 'chg': -0.032, 'usd': 0.92, 'inr': 8.8, 'dir': 'BUY', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'Maruti Suzuki India Limited', 'ow': 1.28, 'nw': 1.249, 'chg': -0.031, 'usd': 0.91, 'inr': 8.7, 'dir': 'BUY', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'Tata Consultancy Services Ltd.', 'ow': 1.27, 'nw': 1.239, 'chg': -0.031, 'usd': 0.91, 'inr': 8.7, 'dir': 'BUY', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'NTPC LTD', 'ow': 1.2, 'nw': 1.171, 'chg': -0.029, 'usd': 0.86, 'inr': 8.2, 'dir': 'BUY', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'Titan Company Ltd.', 'ow': 1.2, 'nw': 1.171, 'chg': -0.029, 'usd': 0.86, 'inr': 8.2, 'dir': 'BUY', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'Hindustan Unilever Ltd.', 'ow': 1.15, 'nw': 1.122, 'chg': -0.028, 'usd': 0.82, 'inr': 7.8, 'dir': 'BUY', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'SHRIRAM FINANCE LTD.', 'ow': 1.13, 'nw': 1.102, 'chg': -0.028, 'usd': 0.81, 'inr': 7.7, 'dir': 'BUY', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'Bharat Electronics Ltd.', 'ow': 1.1, 'nw': 1.073, 'chg': -0.027, 'usd': 0.78, 'inr': 7.5, 'dir': 'BUY', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'Tata Steel Ltd.', 'ow': 1.08, 'nw': 1.053, 'chg': -0.027, 'usd': 0.77, 'inr': 7.4, 'dir': 'BUY', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'Hindalco Industries Ltd', 'ow': 0.95, 'nw': 0.927, 'chg': -0.023, 'usd': 0.68, 'inr': 6.5, 'dir': 'BUY', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'Power Grid Corporation Of India Ltd.', 'ow': 0.92, 'nw': 0.897, 'chg': -0.023, 'usd': 0.66, 'inr': 6.3, 'dir': 'BUY', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'Ultratech Cement Ltd.', 'ow': 0.89, 'nw': 0.868, 'chg': -0.022, 'usd': 0.63, 'inr': 6.1, 'dir': 'BUY', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'Inter Globe Aviation Ltd', 'ow': 0.78, 'nw': 0.761, 'chg': -0.019, 'usd': 0.56, 'inr': 5.3, 'dir': 'BUY', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'Asian Paints Ltd.', 'ow': 0.78, 'nw': 0.761, 'chg': -0.019, 'usd': 0.56, 'inr': 5.3, 'dir': 'BUY', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'Eicher Motors Ltd.', 'ow': 0.75, 'nw': 0.732, 'chg': -0.018, 'usd': 0.53, 'inr': 5.1, 'dir': 'BUY', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'HCL TECHNOLOGIES LTD.', 'ow': 0.73, 'nw': 0.712, 'chg': -0.018, 'usd': 0.52, 'inr': 5.0, 'dir': 'BUY', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'Trent Ltd', 'ow': 0.67, 'nw': 0.654, 'chg': -0.016, 'usd': 0.48, 'inr': 4.6, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'Apollo Hospitals Enterprises Ltd.', 'ow': 0.67, 'nw': 0.654, 'chg': -0.016, 'usd': 0.48, 'inr': 4.6, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'ITC Ltd.', 'ow': 0.66, 'nw': 0.644, 'chg': -0.016, 'usd': 0.47, 'inr': 4.5, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'Grasim Industries Ltd.', 'ow': 0.65, 'nw': 0.634, 'chg': -0.016, 'usd': 0.46, 'inr': 4.4, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'TVS Motors Company Ltd', 'ow': 0.63, 'nw': 0.615, 'chg': -0.015, 'usd': 0.45, 'inr': 4.3, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'NESTLE INDIA LTD.', 'ow': 0.62, 'nw': 0.605, 'chg': -0.015, 'usd': 0.44, 'inr': 4.2, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'MAX HEALTHCARE INSTITUTE LTD.', 'ow': 0.61, 'nw': 0.595, 'chg': -0.015, 'usd': 0.43, 'inr': 4.2, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'SBI Life Insurance Company Ltd', 'ow': 0.61, 'nw': 0.595, 'chg': -0.015, 'usd': 0.43, 'inr': 4.2, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'Divi s Laboratories Ltd.', 'ow': 0.6, 'nw': 0.585, 'chg': -0.015, 'usd': 0.43, 'inr': 4.1, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'TML COMMERCIAL VEHICLES LIMITED', 'ow': 0.6, 'nw': 0.585, 'chg': -0.015, 'usd': 0.43, 'inr': 4.1, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'Cholamandalam Investment and Finance Company Ltd.', 'ow': 0.59, 'nw': 0.576, 'chg': -0.014, 'usd': 0.42, 'inr': 4.0, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'BSE LTD.', 'ow': 0.59, 'nw': 0.576, 'chg': -0.014, 'usd': 0.42, 'inr': 4.0, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'JSW Steel Ltd.', 'ow': 0.58, 'nw': 0.566, 'chg': -0.014, 'usd': 0.41, 'inr': 4.0, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'Tech Mahindra Ltd.', 'ow': 0.58, 'nw': 0.566, 'chg': -0.014, 'usd': 0.41, 'inr': 4.0, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'Cummins India Ltd.', 'ow': 0.57, 'nw': 0.556, 'chg': -0.014, 'usd': 0.41, 'inr': 3.9, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'Cipla Ltd.', 'ow': 0.57, 'nw': 0.556, 'chg': -0.014, 'usd': 0.41, 'inr': 3.9, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'HINDUSTAN AERONAUTICS LTD.', 'ow': 0.56, 'nw': 0.546, 'chg': -0.014, 'usd': 0.4, 'inr': 3.8, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'Bajaj Finserv Ltd.', 'ow': 0.53, 'nw': 0.517, 'chg': -0.013, 'usd': 0.38, 'inr': 3.6, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'ADANI POWER LTD.', 'ow': 0.53, 'nw': 0.517, 'chg': -0.013, 'usd': 0.38, 'inr': 3.6, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'Coal India Ltd.', 'ow': 0.52, 'nw': 0.507, 'chg': -0.013, 'usd': 0.37, 'inr': 3.5, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'DR REDDYS LABORATORIES LTD.', 'ow': 0.52, 'nw': 0.507, 'chg': -0.013, 'usd': 0.37, 'inr': 3.5, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'Bajaj Auto Ltd.', 'ow': 0.5, 'nw': 0.488, 'chg': -0.012, 'usd': 0.36, 'inr': 3.4, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'TATA MOTORS PASSENGER VEHICLES LTD.', 'ow': 0.5, 'nw': 0.488, 'chg': -0.012, 'usd': 0.36, 'inr': 3.4, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'AVENUE SUPERMARTS LTD.', 'ow': 0.49, 'nw': 0.478, 'chg': -0.012, 'usd': 0.35, 'inr': 3.3, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'VARUN BEVERAGES LTD', 'ow': 0.49, 'nw': 0.478, 'chg': -0.012, 'usd': 0.35, 'inr': 3.3, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'GE VERNOVA T&D INDIA LIMITED', 'ow': 0.49, 'nw': 0.478, 'chg': -0.012, 'usd': 0.35, 'inr': 3.3, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'SAMVARDHANA MOTHERSON INTERNATIONAL LIMITED', 'ow': 0.48, 'nw': 0.468, 'chg': -0.012, 'usd': 0.34, 'inr': 3.3, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'VEDANTA ALUMINIUM METAL LTD', 'ow': 0.47, 'nw': 0.458, 'chg': -0.012, 'usd': 0.34, 'inr': 3.2, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'Oil & Natural Gas Corporation Ltd.', 'ow': 0.47, 'nw': 0.458, 'chg': -0.012, 'usd': 0.34, 'inr': 3.2, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'SUZLON ENERGY LTD.', 'ow': 0.47, 'nw': 0.458, 'chg': -0.012, 'usd': 0.34, 'inr': 3.2, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'INDIAN HOTELS COMPANY LTD.', 'ow': 0.47, 'nw': 0.458, 'chg': -0.012, 'usd': 0.34, 'inr': 3.2, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'FEDERAL BANK LTD.', 'ow': 0.46, 'nw': 0.449, 'chg': -0.011, 'usd': 0.33, 'inr': 3.1, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'CG POWER AND INDUSTRIAL SOLUTIONS LIMITED', 'ow': 0.46, 'nw': 0.449, 'chg': -0.011, 'usd': 0.33, 'inr': 3.1, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'Tata Consumer Products Ltd', 'ow': 0.45, 'nw': 0.439, 'chg': -0.011, 'usd': 0.32, 'inr': 3.1, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'Tata Power Co. Ltd.', 'ow': 0.45, 'nw': 0.439, 'chg': -0.011, 'usd': 0.32, 'inr': 3.1, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'AU Small Finance Bank Ltd.', 'ow': 0.44, 'nw': 0.429, 'chg': -0.011, 'usd': 0.31, 'inr': 3.0, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'Hero MotoCorp Ltd.', 'ow': 0.44, 'nw': 0.429, 'chg': -0.011, 'usd': 0.31, 'inr': 3.0, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'PB FINTECH LTD.', 'ow': 0.43, 'nw': 0.419, 'chg': -0.011, 'usd': 0.31, 'inr': 2.9, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'HDFC Life Insurance Company Ltd.', 'ow': 0.43, 'nw': 0.419, 'chg': -0.011, 'usd': 0.31, 'inr': 2.9, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'Power Finance Corporation Ltd.', 'ow': 0.43, 'nw': 0.419, 'chg': -0.011, 'usd': 0.31, 'inr': 2.9, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'Britannia Industries Ltd.', 'ow': 0.43, 'nw': 0.419, 'chg': -0.011, 'usd': 0.31, 'inr': 2.9, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'Lupin Ltd.', 'ow': 0.42, 'nw': 0.41, 'chg': -0.01, 'usd': 0.3, 'inr': 2.9, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'IndusInd Bank Ltd.', 'ow': 0.41, 'nw': 0.4, 'chg': -0.01, 'usd': 0.29, 'inr': 2.8, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'Polycab India Ltd.', 'ow': 0.4, 'nw': 0.39, 'chg': -0.01, 'usd': 0.29, 'inr': 2.7, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'Bharat Heavy Electricals Ltd.', 'ow': 0.39, 'nw': 0.38, 'chg': -0.01, 'usd': 0.28, 'inr': 2.7, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'BHARAT FORGE LTD.', 'ow': 0.39, 'nw': 0.38, 'chg': -0.01, 'usd': 0.28, 'inr': 2.7, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'HDFC Asset Management Company Ltd.', 'ow': 0.39, 'nw': 0.38, 'chg': -0.01, 'usd': 0.28, 'inr': 2.7, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'Bharat Petroleum Corporation Ltd.', 'ow': 0.38, 'nw': 0.371, 'chg': -0.009, 'usd': 0.27, 'inr': 2.6, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'Indus Towers Ltd.', 'ow': 0.38, 'nw': 0.371, 'chg': -0.009, 'usd': 0.27, 'inr': 2.6, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'Torrent Pharmaceuticals Ltd.', 'ow': 0.36, 'nw': 0.351, 'chg': -0.009, 'usd': 0.26, 'inr': 2.5, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'Fortis Healthcare India Ltd', 'ow': 0.36, 'nw': 0.351, 'chg': -0.009, 'usd': 0.26, 'inr': 2.5, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'ASHOK LEYLAND LTD.', 'ow': 0.34, 'nw': 0.332, 'chg': -0.008, 'usd': 0.24, 'inr': 2.3, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'Pidilite Industries Ltd.', 'ow': 0.34, 'nw': 0.332, 'chg': -0.008, 'usd': 0.24, 'inr': 2.3, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'ONE 97 COMMUNICATIONS LTD.', 'ow': 0.34, 'nw': 0.332, 'chg': -0.008, 'usd': 0.24, 'inr': 2.3, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'PERSISTENT SYSTEMS LIMITED', 'ow': 0.34, 'nw': 0.332, 'chg': -0.008, 'usd': 0.24, 'inr': 2.3, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'ICICI LOMBARD GENERAL INSURANCE COMPANY LTD', 'ow': 0.33, 'nw': 0.322, 'chg': -0.008, 'usd': 0.24, 'inr': 2.2, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'REC LTD', 'ow': 0.33, 'nw': 0.322, 'chg': -0.008, 'usd': 0.24, 'inr': 2.2, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'SOLAR INDUSTRIES INDIA LIMITED', 'ow': 0.33, 'nw': 0.322, 'chg': -0.008, 'usd': 0.24, 'inr': 2.2, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'Marico Ltd.', 'ow': 0.33, 'nw': 0.322, 'chg': -0.008, 'usd': 0.24, 'inr': 2.2, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'DIXON TECHNOLOGIES INDIA LTD.', 'ow': 0.33, 'nw': 0.322, 'chg': -0.008, 'usd': 0.24, 'inr': 2.2, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'HITACHI ENERGY INDIA LIMITED', 'ow': 0.33, 'nw': 0.322, 'chg': -0.008, 'usd': 0.24, 'inr': 2.2, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'Aurobindo Pharma Ltd.', 'ow': 0.32, 'nw': 0.312, 'chg': -0.008, 'usd': 0.23, 'inr': 2.2, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'WIPRO LTD.', 'ow': 0.32, 'nw': 0.312, 'chg': -0.008, 'usd': 0.23, 'inr': 2.2, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'GAIL (India) Ltd.', 'ow': 0.31, 'nw': 0.302, 'chg': -0.008, 'usd': 0.22, 'inr': 2.1, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'UNITED SPIRITS LTD.', 'ow': 0.3, 'nw': 0.293, 'chg': -0.007, 'usd': 0.21, 'inr': 2.0, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'Vedanta Ltd.', 'ow': 0.3, 'nw': 0.293, 'chg': -0.007, 'usd': 0.21, 'inr': 2.0, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'Godrej Consumer Products Ltd.', 'ow': 0.3, 'nw': 0.293, 'chg': -0.007, 'usd': 0.21, 'inr': 2.0, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'Indian Oil Corporation Ltd', 'ow': 0.3, 'nw': 0.293, 'chg': -0.007, 'usd': 0.21, 'inr': 2.0, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'FSN E-COMMERCE VENTURES LTD.', 'ow': 0.29, 'nw': 0.283, 'chg': -0.007, 'usd': 0.21, 'inr': 2.0, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'Vodafone Idea Ltd', 'ow': 0.29, 'nw': 0.283, 'chg': -0.007, 'usd': 0.21, 'inr': 2.0, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'HINDUSTAN PETROLEUM CORPORATION LTD', 'ow': 0.29, 'nw': 0.283, 'chg': -0.007, 'usd': 0.21, 'inr': 2.0, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'Jindal Steel & Power Ltd.', 'ow': 0.29, 'nw': 0.283, 'chg': -0.007, 'usd': 0.21, 'inr': 2.0, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'DLF Ltd.', 'ow': 0.29, 'nw': 0.283, 'chg': -0.007, 'usd': 0.21, 'inr': 2.0, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'YES BANK LTD', 'ow': 0.28, 'nw': 0.273, 'chg': -0.007, 'usd': 0.2, 'inr': 1.9, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'PHOENIX MILLS LTD.', 'ow': 0.28, 'nw': 0.273, 'chg': -0.007, 'usd': 0.2, 'inr': 1.9, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'SRF Ltd.', 'ow': 0.28, 'nw': 0.273, 'chg': -0.007, 'usd': 0.2, 'inr': 1.9, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'MULTI COMMODITY EXCHANGE OF INDIA LIMITED', 'ow': 0.27, 'nw': 0.263, 'chg': -0.007, 'usd': 0.19, 'inr': 1.8, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'IDFC First Bank Limited', 'ow': 0.26, 'nw': 0.254, 'chg': -0.006, 'usd': 0.19, 'inr': 1.8, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'INFO EDGE (INDIA) LTD.', 'ow': 0.26, 'nw': 0.254, 'chg': -0.006, 'usd': 0.19, 'inr': 1.8, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'APL APOLLO TUBES LTD.', 'ow': 0.25, 'nw': 0.244, 'chg': -0.006, 'usd': 0.18, 'inr': 1.7, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'ABB INDIA LTD', 'ow': 0.25, 'nw': 0.244, 'chg': -0.006, 'usd': 0.18, 'inr': 1.7, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'SWIGGY LTD', 'ow': 0.25, 'nw': 0.244, 'chg': -0.006, 'usd': 0.18, 'inr': 1.7, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'Muthoot Finance Ltd', 'ow': 0.25, 'nw': 0.244, 'chg': -0.006, 'usd': 0.18, 'inr': 1.7, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'Aditya Birla Capital Ltd.', 'ow': 0.24, 'nw': 0.234, 'chg': -0.006, 'usd': 0.17, 'inr': 1.6, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'SIEMENS ENERGY INDIA LTD', 'ow': 0.24, 'nw': 0.234, 'chg': -0.006, 'usd': 0.17, 'inr': 1.6, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'TUBE INVESTMENTS OF INDIA LTD.', 'ow': 0.24, 'nw': 0.234, 'chg': -0.006, 'usd': 0.17, 'inr': 1.6, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'GMR AIRPORTS LIMITED', 'ow': 0.23, 'nw': 0.224, 'chg': -0.006, 'usd': 0.16, 'inr': 1.6, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'MRF Limited', 'ow': 0.23, 'nw': 0.224, 'chg': -0.006, 'usd': 0.16, 'inr': 1.6, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'Bajaj Holdings and Investment Ltd.', 'ow': 0.22, 'nw': 0.215, 'chg': -0.005, 'usd': 0.16, 'inr': 1.5, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'Bank Of Baroda', 'ow': 0.22, 'nw': 0.215, 'chg': -0.005, 'usd': 0.16, 'inr': 1.5, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'Siemens Ltd.', 'ow': 0.22, 'nw': 0.215, 'chg': -0.005, 'usd': 0.16, 'inr': 1.5, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'UPL Ltd', 'ow': 0.22, 'nw': 0.215, 'chg': -0.005, 'usd': 0.16, 'inr': 1.5, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'NATIONAL ALUMINIUM COMPANY LTD', 'ow': 0.22, 'nw': 0.215, 'chg': -0.005, 'usd': 0.16, 'inr': 1.5, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'Sundaram Finance Ltd.', 'ow': 0.22, 'nw': 0.215, 'chg': -0.005, 'usd': 0.16, 'inr': 1.5, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'VISHAL MEGA MART LIMITED', 'ow': 0.21, 'nw': 0.205, 'chg': -0.005, 'usd': 0.15, 'inr': 1.4, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'Bosch Ltd.', 'ow': 0.21, 'nw': 0.205, 'chg': -0.005, 'usd': 0.15, 'inr': 1.4, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'PRESTIGE ESTATES PROJECTS LIMITED', 'ow': 0.21, 'nw': 0.205, 'chg': -0.005, 'usd': 0.15, 'inr': 1.4, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'LODHA DEVELOPERS LTD.', 'ow': 0.2, 'nw': 0.195, 'chg': -0.005, 'usd': 0.14, 'inr': 1.4, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'NMDC Ltd.', 'ow': 0.2, 'nw': 0.195, 'chg': -0.005, 'usd': 0.14, 'inr': 1.4, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'Page Industries Ltd', 'ow': 0.2, 'nw': 0.195, 'chg': -0.005, 'usd': 0.14, 'inr': 1.4, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'MANKIND PHARMA LTD', 'ow': 0.2, 'nw': 0.195, 'chg': -0.005, 'usd': 0.14, 'inr': 1.4, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'WAAREE ENERGIES LIMITED', 'ow': 0.2, 'nw': 0.195, 'chg': -0.005, 'usd': 0.14, 'inr': 1.4, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'UNION BANK OF INDIA', 'ow': 0.2, 'nw': 0.195, 'chg': -0.005, 'usd': 0.14, 'inr': 1.4, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'Mphasis Ltd', 'ow': 0.2, 'nw': 0.195, 'chg': -0.005, 'usd': 0.14, 'inr': 1.4, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'VOLTAS LTD.', 'ow': 0.19, 'nw': 0.185, 'chg': -0.005, 'usd': 0.14, 'inr': 1.3, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'Ambuja Cements Ltd.', 'ow': 0.19, 'nw': 0.185, 'chg': -0.005, 'usd': 0.14, 'inr': 1.3, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'TORRENT POWER LTD', 'ow': 0.19, 'nw': 0.185, 'chg': -0.005, 'usd': 0.14, 'inr': 1.3, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'GODREJ PROPERTIES LIMITED', 'ow': 0.19, 'nw': 0.185, 'chg': -0.005, 'usd': 0.14, 'inr': 1.3, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'L&T FINANCE LTD', 'ow': 0.19, 'nw': 0.185, 'chg': -0.005, 'usd': 0.14, 'inr': 1.3, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'PUNJAB NATIONAL BANK', 'ow': 0.19, 'nw': 0.185, 'chg': -0.005, 'usd': 0.14, 'inr': 1.3, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'Colgate Palmolive (India ) Ltd.', 'ow': 0.19, 'nw': 0.185, 'chg': -0.005, 'usd': 0.14, 'inr': 1.3, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'CANARA BANK', 'ow': 0.18, 'nw': 0.176, 'chg': -0.004, 'usd': 0.13, 'inr': 1.2, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'ORACLE FINANCIAL SERVICES SOFTWARE LTD', 'ow': 0.18, 'nw': 0.176, 'chg': -0.004, 'usd': 0.13, 'inr': 1.2, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'Coromandel International Ltd.', 'ow': 0.18, 'nw': 0.176, 'chg': -0.004, 'usd': 0.13, 'inr': 1.2, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'Havells India Ltd.', 'ow': 0.18, 'nw': 0.176, 'chg': -0.004, 'usd': 0.13, 'inr': 1.2, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'Alkem Laboratories Ltd.', 'ow': 0.18, 'nw': 0.176, 'chg': -0.004, 'usd': 0.13, 'inr': 1.2, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'Tata Communications Ltd.', 'ow': 0.17, 'nw': 0.166, 'chg': -0.004, 'usd': 0.12, 'inr': 1.2, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'JSW ENERGY LTD.', 'ow': 0.17, 'nw': 0.166, 'chg': -0.004, 'usd': 0.12, 'inr': 1.2, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'INDIAN BANK', 'ow': 0.17, 'nw': 0.166, 'chg': -0.004, 'usd': 0.12, 'inr': 1.2, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'LTIMINDTREE LIMITED', 'ow': 0.17, 'nw': 0.166, 'chg': -0.004, 'usd': 0.12, 'inr': 1.2, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'OBEROI REALTY LTD', 'ow': 0.16, 'nw': 0.156, 'chg': -0.004, 'usd': 0.11, 'inr': 1.1, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'SHREE CEMENT LTD.', 'ow': 0.16, 'nw': 0.156, 'chg': -0.004, 'usd': 0.11, 'inr': 1.1, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'Zydus Lifesciences Limited', 'ow': 0.16, 'nw': 0.156, 'chg': -0.004, 'usd': 0.11, 'inr': 1.1, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'NHPC LIMITED', 'ow': 0.16, 'nw': 0.156, 'chg': -0.004, 'usd': 0.11, 'inr': 1.1, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'PETRONET LNG LTD.', 'ow': 0.16, 'nw': 0.156, 'chg': -0.004, 'usd': 0.11, 'inr': 1.1, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'JINDAL STAINLESS LTD', 'ow': 0.15, 'nw': 0.146, 'chg': -0.004, 'usd': 0.11, 'inr': 1.0, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'SUPREME INDUSTRIES LIMITED', 'ow': 0.15, 'nw': 0.146, 'chg': -0.004, 'usd': 0.11, 'inr': 1.0, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'ICICI Prudential Life Insurance Company Ltd', 'ow': 0.14, 'nw': 0.137, 'chg': -0.003, 'usd': 0.1, 'inr': 1.0, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'Dabur India Ltd.', 'ow': 0.14, 'nw': 0.137, 'chg': -0.003, 'usd': 0.1, 'inr': 1.0, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'OIL INDIA LIMITED', 'ow': 0.13, 'nw': 0.127, 'chg': -0.003, 'usd': 0.09, 'inr': 0.9, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'P I INDUSTRIES LTD', 'ow': 0.13, 'nw': 0.127, 'chg': -0.003, 'usd': 0.09, 'inr': 0.9, 'dir': 'Neutral', 'conf': 'Modelled residual allocation', 'status': 'Post-review constituent'},
    {'stock': 'JIO FINANCIAL SERVICES LTD', 'ow': 0.52, 'nw': 0.408, 'chg': -0.112, 'usd': -61.0, 'inr': -583.2, 'dir': 'SELL', 'conf': 'Reported Nuvama estimate', 'status': 'Post-review constituent'},
    {'stock': 'ASTRAL LTD.', 'ow': 0.1, 'nw': 0.0, 'chg': -0.1, 'usd': -138.0, 'inr': -1319.3, 'dir': 'SELL', 'conf': 'Reported Nuvama estimate', 'status': 'Removed from Standard Index'},
    {'stock': 'SBI CARDS & PAYMENT SERVICES PVT. LTD.', 'ow': 0.11, 'nw': 0.0, 'chg': -0.11, 'usd': -143.0, 'inr': -1367.1, 'dir': 'SELL', 'conf': 'Reported Nuvama estimate', 'status': 'Removed from Standard Index'},
    {'stock': 'Balkrishna Industries Ltd.', 'ow': 0.12, 'nw': 0.0, 'chg': -0.12, 'usd': -169.0, 'inr': -1615.6, 'dir': 'SELL', 'conf': 'Reported Nuvama estimate', 'status': 'Removed from Standard Index'},
    {'stock': 'RELIANCE INDUSTRIES LTD.', 'ow': 6.06, 'nw': 5.055, 'chg': -1.005, 'usd': -523.0, 'inr': -4999.9, 'dir': 'SELL', 'conf': 'Reported Nuvama estimate', 'status': 'Post-review constituent'},
]

METHODOLOGY = {
    "review": "MSCI India Standard Index — August 2026 review",
    "effective": "September 1, 2026 (after August 31 close)",
    "pre_count": 165,
    "post_count": 166,
    "usd_inr": 95.6,
    "published_total": "$1,435m",
    "rounded_total": "$1,500m",
    "calibration": "$600m \u2248 1.00 percentage-point weight change; inferred from published flow estimates",
    "limitation": "MSCI has not publicly released the complete post-review constituent-weight file. "
                  "Estimated weights are a scenario model, not official MSCI weights.",
}


def _norm(name: str) -> str:
    s = name.lower()
    s = re.sub(r"ltd\.?|limited|pvt\.?|\.|,|\(|\)|&", "", s)
    s = re.sub(r"\s+", " ", s).strip()
    return s


def match_msci(company_name: str):
    """Best-effort fuzzy match from a dashboard company name to an MSCI row."""
    target = _norm(company_name)
    target_first = target.split(" ")[0] if target else ""
    for row in MSCI_FLOWS:
        fn = _norm(row["stock"])
        fn_first = fn.split(" ")[0] if fn else ""
        if fn in target or target in fn:
            return row
        if fn_first and len(fn_first) > 3 and fn_first == target_first:
            return row
    return None
